Cgd 26 employee page
curriculum-vitae-team/cv-Kotiagova-Shaidorov pull request #5
Opened 2022-12-06 09:06 UTC by lnicepei

Deploy: https://cv-builder-ashen.vercel.app (open in new tab)

![image](https://user-images.githubusercontent.com/95967146/205867716-15906708-4389-4684-9e06-c54e2e939e14.png)

2022-12-07 06:31 UTC, Ascilator requested changes
![изображение](https://user-images.githubusercontent.com/67093050/206105519-33f906fa-315a-4491-94d0-e558b09c09df.png)

Why i can edit someones profile? also why i don't see department etc

2022-12-07 06:31 UTC, Ascilator commented on src/types/declarations.d.ts
> +      skills?:
why not just [Skill]

2022-12-07 06:31 UTC, Ascilator commented on src/types/declarations.d.ts
> +      languages?:
same

2022-12-07 06:31 UTC, Ascilator commented on src/types/declarations.d.ts
> +    cvs?: CV[] | []
same

2022-12-07 12:20 UTC, lnicepei commented
If you are logged in as uladzislau.yarmashuk@innowise-group.com(as admin), you can edit other profiles. If you log in as an employee, you can edit your own profile. And in case of a regular user, you cannot edit at all.

2023-01-03 09:49 UTC, Ascilator requested changes

2023-01-03 09:49 UTC, Ascilator commented on src/GraphQL/queries.ts
> +
enter? why?

2023-01-03 09:49 UTC, Ascilator commented on src/pages/EmployeePage/EmployeePage.tsx
> +    { label: 'CVs', key: 'cvs', children: <CVs CVsData={employee?.cvs} canEdit={canEdit} /> }
it should be the same style that in above

2023-01-03 09:49 UTC, Ascilator commented on src/pages/EmployeePage/hooks/useGetEmployee.ts
> +const useGetEmployee = () => {
why this logic? why not just a hook that requests emp and returns him. Why do you need this complicate callback

2023-01-06 08:45 UTC, merged